version: "3.9"

services:
  telegram-joke-bot:
    image: pythontelegrambottemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
